# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>From Login</title>
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <form>
      <h2>Create Account</h2>
      <input type="text" placeholder="Full Name" />
      <input type="email" placeholder="Email Address" />
      <input type="password" placeholder="Password" />
      <input type="password" placeholder="Confirm Password" />
      <button>Register</button>
      <p>Already have an account? <a href="#">Log in</a></p>
    </form>
  </body>
</html>

*{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}
body{
    font-family: Arial, sans-serif;
    background-image: linear-gradient(to left, rgb(47, 0, 255),rgb(128, 0, 0));
    background-repeat: no-repeat;
    background-size: cover;
    height: 100vh;
    display: flex;
    align-items: center;
    justify-content: center;
}
form{
    width: 100%;
    max-width: 400px;
    min-width: 280px;
    padding: 30px;
    background-color: rgba(255, 255, 255, 0.9);
    border-radius: 10px;
    border: 1px solid rgba(255, 255, 255, 0.6);
    box-shadow: 0 4px 15px rgba(0, 0, 0, 0.2);
    text-align: center;
    display: flex;
    flex-direction: column;
    
}
form h2{
font-size: 30px;
margin-bottom: 20px;
color: rgb(50, 50, 182);
}
form input,
form button {
    width: 100%;
    padding: 10px;
    margin: 10px 0;
    border: 1px solid #ccc;
    border-radius: 5px;
    font-size: 16px;
}
form input:focus {
    border-color: rgb(47, 0, 255);
    outline: none;
}
form button {
    background-color: rgb(47, 0, 255);
    color: white;
    border: none;
    cursor: pointer;
    transition: background-color 0.3s ease;
}
form button:hover {
    background-color: rgb(128, 0, 0);
}
a {
    color: rgb(47, 0, 255);
    text-decoration: none;
}

a:hover {
    text-decoration: underline;
}
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
